name: cs6742_a2
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pytables
  - python=3.9
  - pip
  - scipy
  - pip:
    - networkx==2.6.3
